print "===== LEXER ====="
dofile "lexer.lua"
print "===== EXPR ====="
dofile "expr.lua"
print "===== STMT ====="
dofile "stmt.lua"
print "===== EXEC ====="
dofile "exec.lua"
print "===== X ====="
dofile "x.lua"
print "===== TASKS ====="
dofile "tasks.lua"
print "===== AWAIT ====="
dofile "await.lua"
print "===== TOGGLE ====="
dofile "toggle.lua"
print "===== CMD ====="
dofile "cmd.lua"
print "===== STREAMS ====="
dofile "streams.lua"
